import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Demo Header */}
        <header
          style={{
            background: "#0070f3",
            color: "white",
            padding: "1rem",
            textAlign: "center",
          }}
        >
          <h1>My App Header</h1>
          <nav>
            <a href="/" style={{ margin: "0 1rem", color: "white" }}>
              Home
            </a>
            <a href="/about" style={{ margin: "0 1rem", color: "white" }}>
              About
            </a>
            <a href="/products" style={{ margin: "0 1rem", color: "white" }}>
              Products
            </a>
          </nav>
        </header>

        {/* Main page content */}
        <main style={{ minHeight: "25vh", padding: "2rem" }}>{children}</main>

        {/* Demo Footer */}
        <footer
          style={{
            background: "#f1f1f1",
            padding: "1rem",
            textAlign: "center",
            marginTop: "2rem",
          }}
        >
          <p>© {new Date().getFullYear()} My App. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
